spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ballcat_codegen?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: '123456'

# 生产环境时不应在配置文件中配置
# 请启动项目时使用 --jasypt.encryptor.password=xxxx 进行传参
jasypt:
  encryptor:
    password: "123456"