spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ballcat_codegen?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: '123456'

